FROM squidfunk/mkdocs-material:9.6.12

ARG TARGETPLATFORM
ARG VERSION
ARG CHANNEL

RUN \
	pip install mkdocs-awesome-nav


LABEL org.opencontainers.image.source="https://github.com/squidfunk/mkdocs-material"
