ARG TARGETPLATFORM
ARG VERSION
ARG CHANNEL

FROM squidfunk/mkdocs-material:${VERSION}

RUN \
	pip install mkdocs-awesome-nav


LABEL org.opencontainers.image.source="https://github.com/squidfunk/mkdocs-material"
